apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus-sa
      containers:
      - image: prom/prometheus
        imagePullPolicy: IfNotPresent
        name: prometheus
        volumeMounts:
          - name: prometheus
            mountPath: /etc/prometheus/
          - name: rules
            mountPath: /etc/rules/      
      - image: prom/alertmanager
        imagePullPolicy: IfNotPresent
        name: alertmanager
        volumeMounts:
          - name: alertmanager
            mountPath: /etc/alertmanager/
      volumes: 
      - name: rules
        configMap:
          defaultMode: 420
          name: rules
      - name: prometheus
        configMap: 
          defaultMode: 420
          name: prometheus
      - name: alertmanager
        configMap: 
          defaultMode: 420
          name: alertmanager
---            
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - port: 9090
    nodePort: 32107
    targetPort: 9090
    protocol: TCP