apiVersion: apps/v1
kind: Deployment
metadata:
  name:  prom-test
  labels:
    name:  prom-test
spec:
  replicas: 1
  selector:
    matchLabels:
      server: prom-test
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        server: prom-test
    spec:
      containers:
        - name: prom-test
          image: usko/prom-test:ver1
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: promsvr
spec:
  selector:
    server: prom-test
  type: NodePort
  ports:
  - nodePort: 30832
    port: 8000
    protocol: TCP
    targetPort: 8000
